image: Visual Studio 2017

skip_commits:
  files:
    - '**/*.md'
build_script: 
    - dotnet restore
    - dotnet build .\AspectCore.APM.sln
artifacts:
    path: '**\*.nupkg'
    type: NuGetPackage
deploy: 
    provider: NuGet
    server: https://www.myget.org/F/aspectcore-apm/api/v2/package
    api_key:
        secure: Omn6oR/ovXpd8PeqJwbAn+nnsceiHiHTOPUyi1a77W2gVuva9PK+/Ip6Xgsq5bEg
    skip_symbols: true